%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 512
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 554.254691191187
   fy: 554.254691191187
   cx: 320.5
   cy: 256.5
